### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by giacco**
Missing args attribute

### CODE REVIEW

**Comment by sytolk** [comment]
Why this is closed args is missing and not work for me?

**Comment by giacco** [comment]
I had proposed that patch because I wasn't able to pass any argument to the script.

But no one seemed interested, so thinking it wasn't the right way to do , I closed it.

**Comment by sytolk** [comment]
@theproductiveprogrammer I can confirm that with this path args works.

**Comment by theproductiveprogrammer** [comment]
@giacco - I'm sorry I missed your PR. If you reopen the PR I will accept it.

**Comment by theproductiveprogrammer** [comment]
Thanks @giacco - I have accepted PR #18 👍

**Pull request closed without merging**
